# Generated by Django 3.2.16 on 2022-10-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='contact_phone',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
