# Generated by Django 3.2.16 on 2022-10-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20221017_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_confirmed',
        ),
        migrations.RemoveField(
            model_name='event',
            name='customer',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_status',
            field=models.IntegerField(choices=[(0, 'Awaiting Confirmation'), (1, 'Confirm Booking'), (2, 'Booking Declined')], default=0),
        ),
    ]
