# Generated by Django 3.2.16 on 2022-10-23 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_alter_booking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
    ]
